runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /.*
  script: focusread.fr
- url: /static
  static_dir: static
  application_readable: true


libraries:
- name: flask
  version: latest 
- name: ssl
  version: latest
